/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.visual;

import hotel.datos.Compra;
import hotel.logico.CCompra;
import hotel.logico.CServicio;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rcs
 */
public class FCompra extends javax.swing.JInternalFrame implements VentanaRegistros{
    public static String idReservacion; 
    public static String cliente; //nombre cliente
    public static String fecha;//fecha de compra
    public static Double totalr; //total de reservacion
    public static String idhab; // id habitacion
    public static String nhab; // numero habitacion
    String accion = "guardar";

    /**
     * Creates new form FCompra
     */
    public FCompra() {
        initComponents();
        this.setTitle("Agregar servicios");
        mostrar(idReservacion);
        txtNombre.setText(cliente);
        txtIDReservacion.setText(idReservacion);
        inhabilitar();
    }
    

   /**
     * El metodo inhabilitar nos permite dejar inactivos los campos para realizar un registro
     * excepto el boton nuevo.
     */
    @Override
    public void inhabilitar() {
        txtIDCompra.setEnabled(false);        
        txtIDReservacion.setEnabled(false);
        txtNombre.setEnabled(false);
        txtIDServicio.setEnabled(false);
        txtServicio.setEnabled(false);
        btnBuscarServicio.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtPrecio.setEnabled(false);
        cboEstado.setEnabled(false);   
        botonNuevo.setEnabled(true);
        botonGuardar.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonEliminar.setEnabled(false);
        botonSalir.setEnabled(true);   
        txtIDServicio.setText("");
        txtIDCompra.setText("");
        //txtIDReservacion.setText("");
        txtPrecio.setText("");
        txtServicio.setText("");
        txtCantidad.setText("");
    }

    /**
     * El metodo habilitar nos permite activar los campos para generar un registro.
     */
    @Override
    public void habilitar() {
        txtIDCompra.setEnabled(false);        
        txtIDReservacion.setEnabled(false);
        txtNombre.setEnabled(false);
        txtIDServicio.setEnabled(false);
        txtServicio.setEnabled(false);
        btnBuscarServicio.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtPrecio.setEnabled(true);
        cboEstado.setEnabled(true);   
        botonNuevo.setEnabled(true);
        botonGuardar.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonEliminar.setEnabled(true);
        botonSalir.setEnabled(true);
        txtIDServicio.setText("");
        txtIDCompra.setText("");
        //txtIDReservacion.setText("");
        txtPrecio.setText("");
        txtServicio.setText("");
        txtCantidad.setText("");
    }

    /**
     * El metodo mostrar nos permite mostrar en la ventana la consulta
     * que se realiza en la base de datos en forma de tabla.
     * @param buscar. El parametro buscar se refiere al parametro por el cual se filtrara la consulta a la base de datos.
     */
    @Override
    public void mostrar(String buscar) {
        try {
            //se crea una tabla
            DefaultTableModel modelo;
            /*se crea un objeto de la clase CCompra para poder operar en la tabla compra.
            de la base de datos*/
            CCompra cc = new CCompra();
            // se almacena la tabla retornada al hacer una consulta en la tabla servicio.
            modelo = cc.consulta(buscar);
            //se muestra en la ventana la tabla recibida por la consulta.
            tablaCompras.setModel(modelo);
            //se obtiene el total de registros existentes en la tabla y se muestra en pantalla
            lbRegistros.setText("Total Registros: " + Integer.toString(cc.totalregistros));
            lbTR.setText("Total Reserv.: $ " + totalr.toString());
            lbTotal.setText("Total a pagar: $" +Double.toString(totalr + cc.totalConsumo));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbServicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbIDCompra = new javax.swing.JLabel();
        txtIDCompra = new javax.swing.JTextField();
        lbReservacion = new javax.swing.JLabel();
        lbDescripcion1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        txtIDReservacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lbServicios = new javax.swing.JLabel();
        txtIDServicio = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        btnBuscarServicio = new javax.swing.JButton();
        lbCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox<>();
        lbDescripcion2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        lbRegistros = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        lbTR = new javax.swing.JLabel();
        lbTR1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbServicio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbServicio.setForeground(new java.awt.Color(102, 0, 0));
        lbServicio.setText("Compra");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Registro de compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        lbIDCompra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbIDCompra.setForeground(new java.awt.Color(0, 0, 0));
        lbIDCompra.setText("ID Compra:");

        txtIDCompra.setBackground(new java.awt.Color(204, 204, 204));
        txtIDCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDCompra.setForeground(new java.awt.Color(0, 0, 0));

        lbReservacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbReservacion.setForeground(new java.awt.Color(0, 0, 0));
        lbReservacion.setText("Reservacion:");

        lbDescripcion1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion1.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion1.setText("Precio:");

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecio.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));

        botonNuevo.setBackground(new java.awt.Color(204, 204, 204));
        botonNuevo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/nuevo.png"))); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(204, 204, 204));
        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/cancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        txtIDReservacion.setBackground(new java.awt.Color(204, 204, 204));
        txtIDReservacion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDReservacion.setForeground(new java.awt.Color(0, 0, 0));
        txtIDReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDReservacionActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lbServicios.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbServicios.setForeground(new java.awt.Color(0, 0, 0));
        lbServicios.setText("Servicio:");

        txtIDServicio.setBackground(new java.awt.Color(204, 204, 204));
        txtIDServicio.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDServicio.setForeground(new java.awt.Color(0, 0, 0));
        txtIDServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDServicioActionPerformed(evt);
            }
        });

        txtServicio.setBackground(new java.awt.Color(204, 204, 204));
        txtServicio.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtServicio.setForeground(new java.awt.Color(0, 0, 0));
        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });

        btnBuscarServicio.setText("...");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        lbCantidad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(0, 0, 0));
        lbCantidad.setText("Cantidad:");

        txtCantidad.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En cargo", "Cancelado" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        lbDescripcion2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion2.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion2.setText("Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addGap(28, 28, 28)
                        .addComponent(botonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIDCompra)
                            .addComponent(lbReservacion)
                            .addComponent(lbServicios)
                            .addComponent(lbDescripcion1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbDescripcion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIDReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(txtIDServicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE))
                                    .addComponent(txtNombre))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDCompra)
                    .addComponent(txtIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReservacion)
                    .addComponent(txtIDReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbServicios)
                    .addComponent(txtIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion1)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonNuevo)
                        .addComponent(botonGuardar)))
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Listado de compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComprasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCompras);

        lbRegistros.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbRegistros.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistros.setText("Registros:");

        botonEliminar.setBackground(new java.awt.Color(204, 204, 204));
        botonEliminar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/eliminar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(204, 204, 204));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/salir.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        lbTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(0, 0, 0));
        lbTotal.setText("Total:");

        lbTR.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTR.setForeground(new java.awt.Color(0, 0, 0));
        lbTR.setText("Total Reserv:");

        lbTR1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTR1.setForeground(new java.awt.Color(0, 0, 0));
        lbTR1.setText("Total Servic.:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTR)
                .addGap(62, 62, 62)
                .addComponent(lbTR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(lbTotal)
                .addGap(81, 81, 81)
                .addComponent(lbRegistros)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbRegistros)
                        .addComponent(lbTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTR)
                        .addComponent(lbTR1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbServicio))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Registro de Compras");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        habilitar();
        botonGuardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //validamos que todos los campos de texto tengan un valor
        if(txtServicio.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un servicio");
            btnBuscarServicio.requestFocus();
            return;
        }
        if (txtCantidad.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una cantidad");
            txtCantidad.requestFocus();
            return;
        }
        if (txtPrecio.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un precio");
            txtPrecio.requestFocus();
            return;
        }

        Compra c = new Compra();
        CCompra cc = new CCompra();
        //guardamos los valores en el objeto de la clase Servicio.
        c.setIdReservacion(Integer.parseInt(txtIDReservacion.getText()));
        c.setIdServicio(Integer.parseInt(txtIDServicio.getText()));
        c.setFecha_compra(Date.valueOf(fecha));
        c.setCantidad(Integer.parseInt(txtCantidad.getText()));
        c.setPrecio(Double.parseDouble(txtPrecio.getText()));
        c.setEstado((String)cboEstado.getItemAt(cboEstado.getSelectedIndex()));
        
        
        if (accion.equals("guardar")){
            if (cc.insertar(c)){
                JOptionPane.showMessageDialog(rootPane, "La compra se registro correctamente");
                mostrar(idReservacion);
                inhabilitar();
            }
        }else if (accion.equals("editar")){
            c.setIdCompra(Integer.parseInt(txtIDCompra.getText()));
            if (cc.editar(c)){
                JOptionPane.showMessageDialog(rootPane, "La compra se edito correctamente");
                mostrar(idReservacion);
                inhabilitar();
            }
        }

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void txtIDReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDReservacionActionPerformed
        txtIDReservacion.transferFocus();
    }//GEN-LAST:event_txtIDReservacionActionPerformed

    private void tablaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComprasMouseClicked
        botonGuardar.setText("Editar");
        habilitar();
        botonEliminar.setEnabled(true);
        accion = "editar";
        int fila = tablaCompras.rowAtPoint(evt.getPoint());
        txtIDCompra.setText(tablaCompras.getValueAt(fila,0).toString());
        txtIDReservacion.setText(tablaCompras.getValueAt(fila,1).toString());
        txtIDServicio.setText(tablaCompras.getValueAt(fila,2).toString());
        txtServicio.setText(tablaCompras.getValueAt(fila,3).toString());
        txtCantidad.setText(tablaCompras.getValueAt(fila,5).toString());
        txtPrecio.setText(tablaCompras.getValueAt(fila,6).toString());
        cboEstado.setSelectedItem(tablaCompras.getValueAt(fila,7).toString());
    }//GEN-LAST:event_tablaComprasMouseClicked

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(!txtIDCompra.getText().equals("")){
            int decision = JOptionPane.showConfirmDialog(rootPane, "Deseas eliminra la compra?","Confirmar",2);
            if(decision == 0){
                CCompra cc = new CCompra();
                Compra c = new Compra();
                c.setIdCompra(Integer.parseInt(txtIDCompra.getText()));
                cc.eliminar(c);
                mostrar(idReservacion);
                inhabilitar();
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDServicioActionPerformed

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
        // TODO add your handling code here:
        FVistaServicios fvs = new FVistaServicios();
        fvs.toFront();
        fvs.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCompra().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbDescripcion2;
    private javax.swing.JLabel lbIDCompra;
    private javax.swing.JLabel lbRegistros;
    private javax.swing.JLabel lbReservacion;
    private javax.swing.JLabel lbServicio;
    private javax.swing.JLabel lbServicios;
    private javax.swing.JLabel lbTR;
    private javax.swing.JLabel lbTR1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIDCompra;
    private javax.swing.JTextField txtIDReservacion;
    public static javax.swing.JTextField txtIDServicio;
    private javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
