/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.visual;

import hotel.datos.Compra;
import hotel.datos.Comprobante;
import hotel.datos.Habitacion;
import hotel.datos.Pago;
import hotel.datos.Reservacion;
import hotel.logico.CCompra;
import hotel.logico.CHabitacion;
import hotel.logico.CPago;
import hotel.logico.CReservacion;
import hotel.logico.CServicio;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Efren
 */
public class FPago extends javax.swing.JInternalFrame implements VentanaRegistros{
    String accion = "guardar";
    public static String idcompra; //id reserva
    public static String cliente; //nombre del cliente
    public static String idhab; //id habitacion
    public static String nhab; //numero habitacion
    public static Double total; //total reservacion y servicios
    /**
     * Creates new form FPago
     */
    public FPago() {
        initComponents();
        mostrar(idcompra);
        inhabilitar();
        txtIDCompra.setText(idcompra);
        txtNCompra.setText(cliente);
        txtIDHabitacion.setText(idhab);
        txtNHabitacion.setText(nhab);
        CCompra cc = new CCompra();
        cc.consulta(idcompra);
        txtTotal.setText(Double.toString(total + cc.totalConsumo));
        
        
    }

    @Override
    public void inhabilitar() {
        txtIDPago.setEnabled(false);
        txtIDCompra.setEnabled(false);
        txtNCompra.setEnabled(false);
        txtIDHabitacion.setEnabled(false);
        txtNHabitacion.setEnabled(false);
        combComprobante.setEnabled(false);
        combComprobante.setEnabled(false);
        txtNComprobante.setEnabled(false);
        combTP.setEnabled(false);
        txtTotal.setEnabled(false);
        dtEmision.setEnabled(false);
        dtPago.setEnabled(false);
        txtIDPago.setText("");
        txtNComprobante.setText("");
        botonGuardar.setEnabled(false);
        botonCancelar.setEnabled(false);
        botonEliminar.setEnabled(false);
        
   }

    @Override
    public void habilitar() {
        txtIDPago.setEnabled(false);
        txtIDCompra.setEnabled(false);
        txtNCompra.setEnabled(false);
        txtIDHabitacion.setEnabled(false);
        txtNHabitacion.setEnabled(false);
        combComprobante.setEnabled(true);
        combTP.setEnabled(true);
        txtNComprobante.setEnabled(true);
        txtTotal.setEnabled(false);
        dtEmision.setEnabled(true);
        dtPago.setEnabled(true);
        txtIDPago.setText("");
        txtNComprobante.setText("");
        botonGuardar.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonEliminar.setEnabled(true);
    }

    @Override
    public void mostrar(String buscar) {
         try {
            //se crea una tabla
            DefaultTableModel modelo;
            /*se crea un objeto de la clase CServicio para poder operar en la tabla servicio.
            de la base de datos*/
            CPago cp = new CPago();
            // se almacena la tabla retornada al hacer una consulta en la tabla servicio.
            modelo = cp.consulta(buscar);
            //se muestra en la ventana la tabla recibida por la consulta.
            tbP.setModel(modelo);
            //se obtiene el total de registros existentes en la tabla y se muestra en pantalla
            lbRegistros.setText("Total pagos: " + Integer.toString(cp.totalregistros));
            
            CCompra cc = new CCompra();
            modelo = cc.consulta(buscar);
            tbL.setModel(modelo);
            lbRegistros1.setText("Total compras: " + cc.totalregistros);
            lbTotal.setText("precio total: $" + cc.totalConsumo);
            lbTotalR.setText("Precio reserva: $" + total.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbP = new javax.swing.JTable();
        lbRegistros = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lbServicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbIDPago = new javax.swing.JLabel();
        txtIDPago = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        lbDescripcion1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        txtIDCompra = new javax.swing.JTextField();
        txtNCompra = new javax.swing.JTextField();
        lbTipo1 = new javax.swing.JLabel();
        txtIDHabitacion = new javax.swing.JTextField();
        txtNHabitacion = new javax.swing.JTextField();
        lbTipo2 = new javax.swing.JLabel();
        combComprobante = new javax.swing.JComboBox<>();
        lbDescripcion2 = new javax.swing.JLabel();
        txtNComprobante = new javax.swing.JTextField();
        lbDescripcion3 = new javax.swing.JLabel();
        lbDescripcion4 = new javax.swing.JLabel();
        dtEmision = new com.toedter.calendar.JDateChooser();
        dtPago = new com.toedter.calendar.JDateChooser();
        lbDescripcion5 = new javax.swing.JLabel();
        combTP = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbL = new javax.swing.JTable();
        lbRegistros1 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbTotalR = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Listado de pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        tbP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbP);

        lbRegistros.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbRegistros.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistros.setText("Registros:");

        botonEliminar.setBackground(new java.awt.Color(204, 204, 204));
        botonEliminar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(204, 204, 204));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbRegistros)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalir)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRegistros))
        );

        lbServicio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbServicio.setForeground(new java.awt.Color(102, 0, 0));
        lbServicio.setText("Pagos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Registro de pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        lbIDPago.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbIDPago.setForeground(new java.awt.Color(0, 0, 0));
        lbIDPago.setText("ID pago:");

        txtIDPago.setBackground(new java.awt.Color(204, 204, 204));
        txtIDPago.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDPago.setForeground(new java.awt.Color(0, 0, 0));

        lbTipo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo.setText("Compra:");

        lbDescripcion1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion1.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion1.setText("Total reserv-servic:");

        txtTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtTotal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 0));

        botonNuevo.setBackground(new java.awt.Color(204, 204, 204));
        botonNuevo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/nuevo.png"))); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(204, 204, 204));
        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/cancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        txtIDCompra.setBackground(new java.awt.Color(204, 204, 204));
        txtIDCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDCompra.setForeground(new java.awt.Color(0, 0, 0));
        txtIDCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCompraActionPerformed(evt);
            }
        });

        txtNCompra.setBackground(new java.awt.Color(204, 204, 204));
        txtNCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtNCompra.setForeground(new java.awt.Color(0, 0, 0));
        txtNCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCompraActionPerformed(evt);
            }
        });

        lbTipo1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbTipo1.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo1.setText("Habitacion:");

        txtIDHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        txtIDHabitacion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtIDHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtIDHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDHabitacionActionPerformed(evt);
            }
        });

        txtNHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        txtNHabitacion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtNHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtNHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNHabitacionActionPerformed(evt);
            }
        });

        lbTipo2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbTipo2.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo2.setText("Tipo comprobante:");

        combComprobante.setBackground(new java.awt.Color(204, 204, 204));
        combComprobante.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        combComprobante.setForeground(new java.awt.Color(0, 0, 0));
        combComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura", "Ticket" }));

        lbDescripcion2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion2.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion2.setText("Num. Comprobante:");

        txtNComprobante.setBackground(new java.awt.Color(204, 204, 204));
        txtNComprobante.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtNComprobante.setForeground(new java.awt.Color(0, 0, 0));

        lbDescripcion3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion3.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion3.setText("Fecha emision:");

        lbDescripcion4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion4.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion4.setText("Fecha pago:");

        lbDescripcion5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbDescripcion5.setForeground(new java.awt.Color(0, 0, 0));
        lbDescripcion5.setText("Tipo de pago:");

        combTP.setBackground(new java.awt.Color(204, 204, 204));
        combTP.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        combTP.setForeground(new java.awt.Color(0, 0, 0));
        combTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(38, 38, 38)
                        .addComponent(botonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIDPago)
                            .addComponent(lbTipo)
                            .addComponent(lbTipo1)
                            .addComponent(lbDescripcion2)
                            .addComponent(lbTipo2)
                            .addComponent(lbDescripcion1)
                            .addComponent(lbDescripcion3)
                            .addComponent(lbDescripcion4)
                            .addComponent(lbDescripcion5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combComprobante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDHabitacion)
                                    .addComponent(txtIDPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(txtIDCompra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNComprobante))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNHabitacion)
                                    .addComponent(txtNCompra)))
                            .addComponent(dtEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combTP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDPago)
                    .addComponent(txtIDPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(txtIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo1)
                    .addComponent(txtIDHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo2)
                    .addComponent(combComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion2)
                    .addComponent(txtNComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combTP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion3)
                    .addComponent(dtEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Listado de servicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        tbL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbL);

        lbRegistros1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbRegistros1.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistros1.setText("Registros:");

        lbTotal.setBackground(new java.awt.Color(204, 204, 204));
        lbTotal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(0, 0, 0));
        lbTotal.setText("jLabel2");

        lbTotalR.setBackground(new java.awt.Color(204, 204, 204));
        lbTotalR.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTotalR.setForeground(new java.awt.Color(0, 0, 0));
        lbTotalR.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbTotalR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTotal)
                .addGap(109, 109, 109)
                .addComponent(lbRegistros1)
                .addGap(101, 101, 101))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegistros1)
                    .addComponent(lbTotal)
                    .addComponent(lbTotalR)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPMouseClicked
        botonGuardar.setText("Editar");
        habilitar();
        botonEliminar.setEnabled(true);
        accion = "editar";
        int fila = tbP.rowAtPoint(evt.getPoint());
        txtIDPago.setText(tbP.getValueAt(fila,0).toString());
        //txtIDCompra.setText(tbP.getValueAt(fila,1).toString());
        dtEmision.setDate(Date.valueOf(tbP.getValueAt(fila, 2).toString()));
        dtPago.setDate(Date.valueOf(tbP.getValueAt(fila, 3).toString()));
        combTP.setSelectedItem(tbP.getValueAt(fila,4).toString());
        combComprobante.setSelectedItem(tbP.getValueAt(fila,5).toString());
        txtNComprobante.setText(tbP.getValueAt(fila,6).toString());
        
        
    }//GEN-LAST:event_tbPMouseClicked

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(!txtIDPago.getText().equals("")){
            int decision = JOptionPane.showConfirmDialog(rootPane, "Deseas eliminra el pago?","Confirmar",2);
            if(decision == 0){
                CPago cs = new CPago();
                Pago s = new Pago();
                s.setIdPago(Integer.parseInt(txtIDPago.getText()));
                cs.eliminar(s);
                mostrar(idcompra);
                inhabilitar();
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        habilitar();
        botonGuardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //validamos que todos los campos de texto tengan un valor
        if(txtNComprobante.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el numero de comprobante");
            txtIDCompra.requestFocus();
            return;
        }
        if (txtTotal.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el total de pago del comprobante");
            txtTotal.requestFocus();
            return;
        }

        Pago s = new Pago();
        CPago cs = new CPago();
        //guardamos los valores en el objeto de la clase Servicio.
        s.setIdCompra(Integer.parseInt(txtIDCompra.getText()));
        s.setTipoPago(combTP.getItemAt(combTP.getSelectedIndex()));
        s.setComprobante(combComprobante.getItemAt(combComprobante.getSelectedIndex()));
        s.setComprobantePago(txtNComprobante.getText());
        s.setTotal(Double.parseDouble(txtTotal.getText()));
        
        Calendar cl;
        cl = dtEmision.getCalendar();
        s.setFecha_emision(new Date(cl.get(Calendar.YEAR)-1900, cl.get(Calendar.MONTH), cl.get(Calendar.DAY_OF_MONTH)));
        cl = dtPago.getCalendar();
        s.setFecha_pago(new Date(cl.get(Calendar.YEAR)-1900, cl.get(Calendar.MONTH), cl.get(Calendar.DAY_OF_MONTH)));
        
        if (accion.equals("guardar")){
            if (cs.insertar(s)){
                JOptionPane.showMessageDialog(rootPane, "El pago se registro correctamente");
                mostrar(idcompra);
                inhabilitar();
                //guardamos comprobante de pago en pdf
                Comprobante.guardar(s,lbTotalR.getText(),lbTotal.getText(),txtNCompra.getText());
                //Desocupar habitacion
                CHabitacion ch = new CHabitacion();
                Habitacion h = new Habitacion();
                h.setIdHabitacion(Integer.parseInt(txtIDHabitacion.getText()));
                ch.desocupar(h);
                //pagar reservacion
                CReservacion cr = new CReservacion();
                Reservacion r = new Reservacion();
                r.setIdReservacion(Integer.parseInt(txtIDCompra.getText()));
                cr.pagar(r);
            }
        }else if (accion.equals("editar")){
            s.setIdPago(Integer.parseInt(txtIDPago.getText()));
            if (cs.editar(s)){
                JOptionPane.showMessageDialog(rootPane, "El pago se edito correctamente");
                mostrar(idcompra);
                inhabilitar();
                //sobre escribimos el archivo pdf.
                Comprobante.guardar(s,lbTotalR.getText(),lbTotal.getText(),txtNCompra.getText());
            }
        }

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void txtIDCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCompraActionPerformed
        txtIDCompra.transferFocus();
    }//GEN-LAST:event_txtIDCompraActionPerformed

    private void txtNCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNCompraActionPerformed

    private void txtIDHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDHabitacionActionPerformed

    private void txtNHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNHabitacionActionPerformed

    private void tbLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> combComprobante;
    private javax.swing.JComboBox<String> combTP;
    private com.toedter.calendar.JDateChooser dtEmision;
    private com.toedter.calendar.JDateChooser dtPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbDescripcion2;
    private javax.swing.JLabel lbDescripcion3;
    private javax.swing.JLabel lbDescripcion4;
    private javax.swing.JLabel lbDescripcion5;
    private javax.swing.JLabel lbIDPago;
    private javax.swing.JLabel lbRegistros;
    private javax.swing.JLabel lbRegistros1;
    private javax.swing.JLabel lbServicio;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipo1;
    private javax.swing.JLabel lbTipo2;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalR;
    private javax.swing.JTable tbL;
    private javax.swing.JTable tbP;
    private javax.swing.JTextField txtIDCompra;
    private javax.swing.JTextField txtIDHabitacion;
    private javax.swing.JTextField txtIDPago;
    private javax.swing.JTextField txtNCompra;
    private javax.swing.JTextField txtNComprobante;
    private javax.swing.JTextField txtNHabitacion;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
