/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.visual;

import hotel.datos.Trabajador;
import hotel.logico.CTrabajador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author drago
 */
public class FTrabajador extends javax.swing.JInternalFrame implements VentanaRegistros{
    String accion = "guardar";

    /**
     * Creates new form FTrabajador
     */
    public FTrabajador() {
        initComponents();
        mostrar("");
        inhabilitar();
    }
    
    /**
     * El metodo ocultar columnas nos permite ocultar en la pantalla las columnas con informacion importnate
     * para el inicio de sesion de una persona.
     */
    void ocultar_columnas(){
        tablaTrabajadores.getColumnModel().getColumn(9).setMaxWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(9).setMinWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(9).setPreferredWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(12).setMaxWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(12).setMinWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(12).setPreferredWidth(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtIDPersona = new javax.swing.JTextField();
        lbPiso = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        combPuesto = new javax.swing.JComboBox<>();
        lbTipo = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        combEstadoLog = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        lbIDHabitacion = new javax.swing.JLabel();
        txtAPaterno = new javax.swing.JTextField();
        lbPiso1 = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        lbPiso2 = new javax.swing.JLabel();
        lbPiso3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbTipo1 = new javax.swing.JLabel();
        lbTipo2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbEstado1 = new javax.swing.JLabel();
        lbEstado2 = new javax.swing.JLabel();
        combPS = new javax.swing.JComboBox<>();
        lbTipo3 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        psContrasena = new javax.swing.JPasswordField();
        psRS = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        lbBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lbRegistros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Trabajador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Registro de trabajador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtIDPersona.setBackground(new java.awt.Color(204, 204, 204));
        txtIDPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPersonaActionPerformed(evt);
            }
        });

        lbPiso.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbPiso.setForeground(new java.awt.Color(0, 0, 0));
        lbPiso.setText("A. Paterno:");

        lbNumero.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(0, 0, 0));
        lbNumero.setText("Nombre:");

        combPuesto.setBackground(new java.awt.Color(204, 204, 204));
        combPuesto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        combPuesto.setForeground(new java.awt.Color(0, 0, 0));
        combPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Botones", "Camarero", "Cocinero", "Conserje", "Gerente", "Mantenimiento", "Seguridad", "Sub-Gerente", "Recepcionista", " " }));
        combPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combPuestoActionPerformed(evt);
            }
        });

        lbTipo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo.setText("Sueldo:");

        lbEstado.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(0, 0, 0));
        lbEstado.setText("Estado Loggeo:");

        combEstadoLog.setBackground(new java.awt.Color(204, 204, 204));
        combEstadoLog.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        combEstadoLog.setForeground(new java.awt.Color(0, 0, 0));
        combEstadoLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactiva", "Activa", " " }));
        combEstadoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combEstadoLogActionPerformed(evt);
            }
        });

        botonNuevo.setBackground(new java.awt.Color(204, 204, 204));
        botonNuevo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/nuevo.png"))); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(204, 204, 204));
        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/cancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        lbIDHabitacion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbIDHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        lbIDHabitacion.setText("ID :");

        txtAPaterno.setBackground(new java.awt.Color(204, 204, 204));
        txtAPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPaternoActionPerformed(evt);
            }
        });

        lbPiso1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbPiso1.setForeground(new java.awt.Color(0, 0, 0));
        lbPiso1.setText("A. Materno:");

        txtAMaterno.setBackground(new java.awt.Color(204, 204, 204));
        txtAMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAMaternoActionPerformed(evt);
            }
        });

        lbPiso2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbPiso2.setForeground(new java.awt.Color(0, 0, 0));
        lbPiso2.setText("Telefono:");

        lbPiso3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbPiso3.setForeground(new java.awt.Color(0, 0, 0));
        lbPiso3.setText("Email:");

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lbTipo1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTipo1.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo1.setText("Usuario:");

        lbTipo2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTipo2.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo2.setText("Contraseña:");

        txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lbEstado1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbEstado1.setForeground(new java.awt.Color(0, 0, 0));
        lbEstado1.setText("Pregunta de seguridad:");

        lbEstado2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbEstado2.setForeground(new java.awt.Color(0, 0, 0));
        lbEstado2.setText("Respuesta de seguridad:");

        combPS.setBackground(new java.awt.Color(204, 204, 204));
        combPS.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        combPS.setForeground(new java.awt.Color(0, 0, 0));
        combPS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cual fue el nombre de tu primer mascota?", "¿Cual es tu comida favorita?", "¿Cual es el nombre de tu madre?", "¿Cual es el apodo de tu mejor amigo?", "¿Cual es tu deporte favorito?", "¿Cual es tu equipo deportivo favorito?" }));
        combPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combPSActionPerformed(evt);
            }
        });

        lbTipo3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbTipo3.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo3.setText("Puesto:");

        txtSueldo.setBackground(new java.awt.Color(204, 204, 204));
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });

        psContrasena.setBackground(new java.awt.Color(204, 204, 204));
        psContrasena.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        psContrasena.setForeground(new java.awt.Color(0, 0, 0));
        psContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psContrasenaActionPerformed(evt);
            }
        });

        psRS.setBackground(new java.awt.Color(204, 204, 204));
        psRS.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        psRS.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(46, 46, 46)
                        .addComponent(botonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEstado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combPS, 0, 281, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbIDHabitacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIDPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbTipo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combEstadoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbPiso)
                                                .addComponent(lbNumero)
                                                .addComponent(lbPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbPiso1)
                                                .addComponent(lbTipo3)
                                                .addComponent(lbPiso3))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(30, 30, 30)
                                                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtAPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(combPuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(psContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbTipo2)
                            .addComponent(lbTipo1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEstado2)
                        .addGap(4, 4, 4)
                        .addComponent(psRS)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIDHabitacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPiso3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combEstadoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combPS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(102, 0, 0)), "Listado de trabajadores", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        tablaTrabajadores.setBackground(new java.awt.Color(204, 204, 204));
        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTrabajadores);

        lbBuscar.setBackground(new java.awt.Color(204, 204, 204));
        lbBuscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lbBuscar.setText("Buscar por email:");
        lbBuscar.setToolTipText("Buscar");

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        botonBuscar.setBackground(new java.awt.Color(204, 204, 204));
        botonBuscar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(204, 204, 204));
        botonEliminar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/eliminar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(204, 204, 204));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(0, 0, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/files/salir.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        lbRegistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbRegistros.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistros.setText("Registros: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbRegistros)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRegistros)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Trabajadores");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(975, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTrabajadoresMouseClicked
        botonGuardar.setText("Editar");
        habilitar();
        botonEliminar.setEnabled(true);
        accion = "editar";
        txtUsuario.setEnabled(false);
        combEstadoLog.setEnabled(false);
        combPS.setEnabled(false);
        psRS.setEnabled(false);
        int fila = tablaTrabajadores.rowAtPoint(evt.getPoint());
        txtIDPersona.setText(tablaTrabajadores.getValueAt(fila,0).toString());
        txtNombre.setText(tablaTrabajadores.getValueAt(fila,1).toString());
        txtAPaterno.setText(tablaTrabajadores.getValueAt(fila,2).toString());
        txtAMaterno.setText(tablaTrabajadores.getValueAt(fila,3).toString());
        txtTelefono.setText(tablaTrabajadores.getValueAt(fila,4).toString());
        txtEmail.setText(tablaTrabajadores.getValueAt(fila,5).toString());
        txtSueldo.setText(tablaTrabajadores.getValueAt(fila,6).toString());
        combPuesto.setSelectedItem(tablaTrabajadores.getValueAt(fila,7).toString());
        txtUsuario.setText(tablaTrabajadores.getValueAt(fila,8).toString());
        psContrasena.setText(tablaTrabajadores.getValueAt(fila,9).toString());
        combEstadoLog.setSelectedItem(tablaTrabajadores.getValueAt(fila,10).toString());
        combPS.setSelectedItem(tablaTrabajadores.getValueAt(fila,11).toString());
        psRS.setText(tablaTrabajadores.getValueAt(fila,12).toString());
        
    }//GEN-LAST:event_tablaTrabajadoresMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(!txtIDPersona.getText().equals("")){
            int decision = JOptionPane.showConfirmDialog(rootPane, "Deseas eliminar el trabajador?","Confirmar",2);
            if(decision == 0){
                CTrabajador ct = new CTrabajador();
                Trabajador t = new Trabajador();
                t.setIdpersona(Integer.parseInt(txtIDPersona.getText()));
                ct.eliminar(t);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void combPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combPSActionPerformed
        combPS.transferFocus();
    }//GEN-LAST:event_combPSActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtUsuario.transferFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtEmail.transferFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        txtTelefono.transferFocus();
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtAMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAMaternoActionPerformed
        txtAMaterno.transferFocus();
    }//GEN-LAST:event_txtAMaternoActionPerformed

    private void txtAPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPaternoActionPerformed
        txtAPaterno.transferFocus();
    }//GEN-LAST:event_txtAPaternoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        habilitar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (txtNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu nombre");
            txtNombre.requestFocus();
            return;
        }
        if (txtAPaterno.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu apellido paterno");
            txtAPaterno.requestFocus();
            return;
        }
        if (txtAMaterno.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu apellido materno");
            txtAMaterno.requestFocus();
            return;
        }
        if (txtTelefono.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu telefono");
            txtTelefono.requestFocus();
            return;
        }else if(txtTelefono.getText().length() < 9){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un telefono con almenos 10 digitos");
            txtTelefono.requestFocus();
            return;
        }
        if (txtEmail.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu email");
            txtEmail.requestFocus();
            return;
        }
        if (txtSueldo.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un sueldo");
            txtSueldo.requestFocus();
            return;
        }
        if (txtUsuario.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu usuario");
            txtUsuario.requestFocus();
            return;
        }
        if (psContrasena.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu contrasena");
            psContrasena.requestFocus();
            return;
        }else if(psContrasena.getText().length() < 7){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una contrasena con almenos 8 caracteres");
            psContrasena.requestFocus();
            return;
        }
        if (psRS.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar tu respuesta");
            psRS.requestFocus();
            return;
        }
        
        
        Trabajador t = new Trabajador();
        CTrabajador ct = new CTrabajador();
        //guardamos los datos de la pantalla en el objeto de Habitacion
        t.setNombre(txtNombre.getText());
        t.setaPaterno(txtAPaterno.getText());
        t.setPuesto(combPuesto.getItemAt(combPuesto.getSelectedIndex()));
        t.setEstado_log(combEstadoLog.getItemAt(combEstadoLog.getSelectedIndex()));
        t.setPreguntaSeguridad(combPS.getItemAt(combPS.getSelectedIndex()));
        
        t.setaMaterno(txtAMaterno.getText());
        t.setTelefono(txtTelefono.getText());
        t.setEmail(txtEmail.getText());
        t.setSueldo(Float.parseFloat(txtSueldo.getText()));
        t.setUsuario(txtUsuario.getText());
        t.setContrasena(psContrasena.getText());
        t.setRespuestaSeguridad(psRS.getText());
        
        
        if (accion.equals("guardar")){
            if (ct.insertar(t)){
                JOptionPane.showMessageDialog(rootPane, "El trabajador se guardo correctamente");
                mostrar("");
                inhabilitar();
            }  
        }else if (accion.equals("editar")){
            t.setIdpersona(Integer.parseInt(txtIDPersona.getText()));
            if (ct.editar(t)){
                JOptionPane.showMessageDialog(rootPane, "El trabajador se edito correctamente");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        habilitar();
        botonGuardar.setText("Guardar");
        accion = "guardar"; 
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void combEstadoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combEstadoLogActionPerformed
        combEstadoLog.transferFocus();
    }//GEN-LAST:event_combEstadoLogActionPerformed

    private void combPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combPuestoActionPerformed
        combPuesto.transferFocus();
    }//GEN-LAST:event_combPuestoActionPerformed

    private void txtIDPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtNombre.transferFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        txtSueldo.transferFocus();
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void psContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psContrasenaActionPerformed
        psContrasena.transferFocus();
    }//GEN-LAST:event_psContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> combEstadoLog;
    private javax.swing.JComboBox<String> combPS;
    private javax.swing.JComboBox<String> combPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbIDHabitacion;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbPiso;
    private javax.swing.JLabel lbPiso1;
    private javax.swing.JLabel lbPiso2;
    private javax.swing.JLabel lbPiso3;
    private javax.swing.JLabel lbRegistros;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipo1;
    private javax.swing.JLabel lbTipo2;
    private javax.swing.JLabel lbTipo3;
    private javax.swing.JPasswordField psContrasena;
    private javax.swing.JPasswordField psRS;
    private javax.swing.JTable tablaTrabajadores;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDPersona;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inhabilitar() {
        botonBuscar.setEnabled(true);
        botonCancelar.setEnabled(false);
        botonEliminar.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonNuevo.setEnabled(true);
        botonSalir.setEnabled(true);
        combEstadoLog.setEnabled(false);
        combPS.setEnabled(false);
        combPuesto.setEnabled(false);
        txtAMaterno.setEnabled(false);
        txtAPaterno.setEnabled(false);
        txtBuscar.setEnabled(true);
        psContrasena.setEnabled(false);
        txtEmail.setEnabled(false);
        txtIDPersona.setEnabled(false);
        txtNombre.setEnabled(false);
        psRS.setEnabled(false);
        txtSueldo.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtAMaterno.setText("");
        txtAPaterno.setText("");
        txtBuscar.setText("");
        psContrasena.setText("");
        txtEmail.setText("");
        txtIDPersona.setText("");
        txtNombre.setText("");
        psRS.setText("");
        txtSueldo.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
    }

    @Override
    public void habilitar() {
        botonBuscar.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonEliminar.setEnabled(true);
        botonGuardar.setEnabled(true);
        botonNuevo.setEnabled(true);
        botonSalir.setEnabled(true);
        combEstadoLog.setEnabled(true);
        combPS.setEnabled(true);
        combPuesto.setEnabled(true);
        txtAMaterno.setEnabled(true);
        txtAPaterno.setEnabled(true);
        txtBuscar.setEnabled(true);
        psContrasena.setEnabled(true);
        txtEmail.setEnabled(true);
        txtIDPersona.setEnabled(false);
        txtNombre.setEnabled(true);
        psRS.setEnabled(true);
        txtSueldo.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtUsuario.setEnabled(true);
        txtAMaterno.setText("");
        txtAPaterno.setText("");
        txtBuscar.setText("");
        psContrasena.setText("");
        txtEmail.setText("");
        txtIDPersona.setText("");
        txtNombre.setText("");
        psRS.setText("");
        txtSueldo.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
    }

    @Override
    public void mostrar(String email) {
        try {
            //se crea una tabla
            DefaultTableModel modelo;
            /*se crea un objeto de la clase CHabitacion para poder operar en la tbala habitacion.
            de la base de datos*/
            CTrabajador ct = new CTrabajador();
            // se almacena la tabla retornada al hacer una consulta en la tabla habitacion.
            modelo = ct.consulta(email);
            //se muestra en la ventana la tabla recibida por la consulta.
            tablaTrabajadores.setModel(modelo);
            ocultar_columnas();
            //se obtiene el total de registros existentes en la tabla y se muestra en pantalla
            lbRegistros.setText("Total Registros: " + Integer.toString(ct.totalregistros));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    
}
